version: "3.5"
services:
  #client:
  #  build:
  #    context: ./client
  #  command: "sh -c \"npm run serve\""
  #  container_name: client
  #  depends_on:
  #    - api
  #  restart: unless-stopped
  #  ports:
  #    - 8080:8080
  #  volumes:
  #    - "./client/src:/app/src"
  #    - "./client/package.json:/app/package.json"
  #    - "./client/package-lock.json:/app/package-lock.json"
  api:
    container_name: api
    build: ./api/
    depends_on:
      - pg
    command: "sh -c \"./wait-for pg:5432 -- npm start\""
    environment: 
      DB_HOST: pg
      DB_USER: postgres
      DB_PASS: password
      DATABASE_URL: postgres://postgres:password@pg:5432/bad-api
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - "./api/src/:/app/src"
      - "./api/package.json:/app/package.json"
      - "./api/package-lock.json:/app/package-lock.json"
  pg:
    build:
      context: ./data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: bad-api
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data: 
