version: "3.5"
services:
  # Client
  #client:
  #  build:
  #    context: ./client
  #  command: "sh -c \"npm run serve\""
  #  container_name: client
  #  depends_on:
  #    - api
  #  restart: unless-stopped
  #  ports:
  #    - 8080:8080
  #  volumes:
  #    - "./client/src:/app/src"
  #    - "./client/package.json:/app/package.json"
  #    - "./client/package-lock.json:/app/package-lock.json"
  # Redis Client API
  api:
    container_name: api
    build: 
      context: ./api/
      dockerfile: Dockerfile
    command: "sh -c \"./wait-for pg:5432 redis:6379 -- npm start\""
    environment:
    ## TODO store DB connections in separate config file
      DB_HOST: pg
      DB_USER: postgres
      DB_PASS: password
      DATABASE_URL: postgres://postgres:password@pg:5432/bad-api
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - pg
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - "./api/src/:/app/src"
      - "./api/package.json:/app/package.json"
      - "./api/package-lock.json:/app/package-lock.json"
  # Proxy API
  proxy:
    container_name: proxy
    build: 
      context: ./data/
      dockerfile: Dockerfile.proxy
    command: "sh -c \"./wait-for pg:5432 redis:6379 -- npm start\""
    environment:
      ## TODO store DB connections in separate config file
      DB_HOST: pg
      DB_USER: postgres
      DB_PASS: password
      DATABASE_URL: postgres://postgres:password@pg:5432/bad-api
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - pg
    restart: unless-stopped
    volumes:
      - "./data/src/:/app/src"
      - "./data/package.json:/app/package.json"
      - "./data/package-lock.json:/app/package-lock.json"
  # Redis
  redis:
    image: redis:alpine
    ## TODO: Redis config file
    #volumes:
    #  - ./redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  #PostGreSQL
  pg:
    build:
      context: ./data/
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: bad-api
      DATABASE_URL: postgres://postgres:password@pg:5432/bad-api
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data: 
