version: "3.5"
services:
  # Client
  client:
    build:
      context: ./client
    command: "sh -c \"npm run serve\""
    container_name: client
    depends_on:
      - api
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - "./client/src:/app/src"
      - "./client/package.json:/app/package.json"
      - "./client/package-lock.json:/app/package-lock.json"
  # API
  api:
    container_name: api
    build: 
      context: ./api/
    command: "sh -c \"npm start\""
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - "./api/src/:/app/src"
      - "./api/package.json:/app/package.json"
      - "./api/package-lock.json:/app/package-lock.json"
  # Redis
  redis:
    image: redis:alpine
    expose:
      - 6379
