version: "3.5"
services:
  # Client
  #client:
  #  build:
  #    context: ./client
  #  command: "sh -c \"npm run serve\""
  #  container_name: client
  #  depends_on:
  #    - api
  #  restart: unless-stopped
  #  ports:
  #    - 8080:8080
  #  volumes:
  #    - "./client/src:/app/src"
  #    - "./client/package.json:/app/package.json"
  #    - "./client/package-lock.json:/app/package-lock.json"
  # Redis Client API
  #api:
  #  container_name: api
  #  build: 
  #    context: ./api/
  #  command: "sh -c \"npm start\""
  #  links:
  #    - redis
  #  environment:
  #    - REDIS_URL=redis://redis:6379
  #  restart: unless-stopped
  #  ports:
  #    - 3001:3001
  #  volumes:
  #    - "./api/src/:/app/src"
  #    - "./api/package.json:/app/package.json"
   #   - "./api/package-lock.json:/app/package-lock.json"
  # Redis
  redis:
    image: redis:alpine
    ## Check if this works
    #volumes:
    #  - ./redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
  # Proxy API
  proxy:
    container_name: proxy
    build: 
      context: ./data/
      dockerfile: Dockerfile.proxy
    command: "sh -c \"npm start\""
    environment:
      - REDIS_URL=redis://redis:6379
      - pg
    depends_on:
      - pg
      - redis
    command: "sh -c \"./wait-for pg:5432 -- npm start\""
    environment: 
      DB_HOST: pg
      DB_USER: postgres
      DB_PASS: password
      DATABASE_URL: postgres://postgres:password@pg:5432/bad-api
    restart: unless-stopped
    # Close ports for production
    ports:
      - 3002:3002
    volumes:
      - "./data/src/:/app/src"
      - "./data/package.json:/app/package.json"
      - "./data/package-lock.json:/app/package-lock.json"
  #PostGreSQL
  pg:
    build:
      context: ./data/
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: bad-api
      DATABASE_URL: postgres://postgres:password@pg:5432/bad-api
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data: 
